In [22]:
import numpy as np
farr=np.zeros((56,20))
arr=np.zeros((56,20))
fileloc='C:/users/rohan/notebook/ass2csv/'
for i in range(1,57):
    print(i)
    fname='C:/users/rohan/notebook/dm/'+str(i)+'.csv'
    arr=np.genfromtxt(fname,delimiter=',')
    for j in range(0,20):
        farr[i-1,j]=misclassificationError(arr[:,j],arr[:,-1])
flocnew=fileloc+'dmexp/misclerror.csv'        
fname=fileloc+'gini.csv'    
np.savetxt(flocnew,farr, delimiter=',', fmt='%f')  
print(farr)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
[[0.16       0.16       0.16       ... 0.16       0.16       0.16      ]
 [0.2247191  0.2247191  0.2247191  ... 0.2247191  0.2247191  0.2247191 ]
 [0.10921502 0.10921502 0.10921502 ... 0.10921502 0.10921502 0.10921502]
 ...
 [0.25680272 0.25680272 0.25680272 ... 0.25680272 0.25680272 0.25680272]
 [0.47530864 0.47530864 0.47530864 ... 0.47530864 0.47530864 0.47530864]
 [0.44827586 0.44827586 0.44827586 ... 0.44827586 0.44827586 0.44827586]]


In [20]:
def square(val):
    return val*val;
import math;
def nos(c,in1):
    in2=np.where(c[in1[0]]==0)
    in3=np.where(c[in1[0]]>0)
    return len(in2[0]),len(in3[0])

def giniscal(f,c):
    mf=np.median(f)
    in1=np.where(f<=mf)
    in2=np.where(f>mf)
    n00,n01=nos(c,in1)
    n10,n11=nos(c,in2)
    if (n00==0 or n01==0):
        p00=0.5
        p01=0.5
    else:
        p00=n00/(n00+n01)
        p01=n01/(n00+n01)
    if(n10==0 or n11==0):
        p10=0.5
        p11=0.5
    else:
        p10=n10/(n10+n11)
        p11=n11/(n10+n11)
    gl=1-p00*p00-p01*p01;
    gr=1-p10*p10-p11*p11;
    fgs=len(in1[0])/(len(in1[0])+len(in2[0]))*gl+len(in2[0])/(len(in1[0])+len(in2[0]))*gr
    return fgs
def infoGain(f,c):
    mf=np.median(f)
    in1=np.where(f<=mf)
    in2=np.where(f>mf)
    n00,n01=nos(c,in1)
    n10,n11=nos(c,in2)
    en0=1
    en1=1
    if(n00==0 or n01==0):
        en0=0
    else:
        p00=n00/(n01+n00);
        p01=n01/(n01+n00);
    if(n10==0 or n11==0):
        en1=0
    else:
        p10=n10/(n10+n11)
        p11=n11/(n10+n11)
    if(en0!=0):
        en0=-1*((p00*(math.log(p00,2)))+(p01*(math.log(p01,2))))
    if(en1!=0):
        en1=-1*((p10*(math.log(p10,2)))+(p11*(math.log(p11,2))))
    val0=n00+n10
    val1=n01+n11
    total=val0+val1;
    part0=n00+n01;
    part1=n10+n11;
    pr0=val0/(val0+val1)
    pr1=val1/(val0+val1)
    enP=-1*((pr0*(math.log(pr0,2)))+(pr1*(math.log(pr1,2))))
    entr=enP-(part0*en0/total)-(part1*en1/total)
    return entr;
def gainRatio(f,c):
    mf=np.median(f)
    in1=np.where(f<=mf)
    in2=np.where(f>mf)
    n00,n01=nos(c,in1)
    n10,n11=nos(c,in2)
    gain=infoGain(f,c)
    part0=n00+n01
    part1=n10+n11
    total=part0+part1
    spart0=part0/total;
    spart1=part1/total;
    if(spart0==0):
        contr0=0
    else:
        contr0=math.log(spart0,2)*spart0
    if(spart1==0):
        contr1=0
    else:
        contr1=(math.log(spart1,2)*spart1)
        
    splitInfo=-1*(contr0+contr1);
    if(splitInfo==0):
        fans=1
    else:
        fans=gain/splitInfo
    return fans
    
def misclassificationError(f,c):
    mf=np.median(f)
    in1=np.where(f<=mf)
    in2=np.where(f>mf)
    n00,n01=nos(c,in1)
    n10,n11=nos(c,in2)
    val0=n00+n10;
    val1=n01+n11;
    pr0=val0/(val0+val1);
    pr1=val1/(val0+val1);
    fans=1-max(pr0,pr1);
    return fans;
def chiValueFun(f,c):
    mf=np.median(f)
    in1=np.where(f<=mf)
    in2=np.where(f>mf)
    n00,n01=nos(c,in1)
    n10,n11=nos(c,in2)
    c1y=n11
    c1n=n10
    c0y=n01
    c0n=n00
    valy=c1y+c0y;
    valn=c1n+c0n;
    val1=c1y+c1n;
    val0=c0y+c0n;
    summ=valy+valn+val1+val0;
    
    auxval1y=valy*val1/summ;
    auxval0y=valy*val0/summ;
    auxval1n=valn*val1/summ;
    auxval0n=valn*val0/summ;
    if(auxval1y==0):
        temp1y=0;
    else:
        temp1y=square(auxval1y-c1y)/auxval1y;
    if(auxval0y==0):
        temp0y=0;
    else:
        temp0y=square(auxval0y-c0y)/auxval0y;
    if(auxval1n==0):
        temp1n=0;
    else:
        temp1n=square(auxval1n-c1n)/auxval1n;
    if(auxval0n==0):
        temp0n=0;
    else:
        temp0n=square(auxval0n-c0n)/auxval0n;   
    
    
    
    return temp1y+temp0y+temp1y+temp0n;
    

In [5]:
#rank the features
def sortandReturnTop(arr):
    dicti={}
    flist=list()
    falist=list()
    for i in range(0,len(arr)):
        falist.append(arr[i])
    for i in range(0,len(arr)):
        dicti[falist[i]]=i
    falist.sort(reverse=True);
    for i in range(0,5):
        flist.append(dicti[falist[i]])
    return flist

In [6]:
print(sortandReturnTop([3,2,1,4,5,6,3,4,2,1]));

[5, 4, 7, 7, 6]


In [25]:
import numpy as np
fans=np.zeros((56,5))
arr=np.zeros((56,20))
fileloc='C:/users/rohan/notebook/ass2csv/dmexp/'
for i in range(4,5):
    print(i)
    fname='C:/users/rohan/notebook/ass2csv/dmexp/abc/'+str(i)+'.csv'
    arr=np.genfromtxt(fname,delimiter=',')
    for j in range(0,56):
        arrin=arr[j:j+1][0]
        imparr=sortandReturnTop(arrin)
        print(imparr)
        for k in range(0,5):
            fans[j][k]=imparr[k]
fname=fileloc+'finalranks4.csv'    
np.savetxt(fname,fans, delimiter=',', fmt='%f')  

4
[0, 10, 10, 3, 6]
[7, 1, 13, 2, 3]
[0, 5, 3, 7, 8]
[10, 4, 0, 7, 5]
[10, 4, 5, 0, 8]
[7, 3, 0, 12, 8]
[10, 10, 7, 7, 6]
[2, 11, 8, 3, 5]
[8, 6, 3, 18, 19]
[8, 4, 0, 18, 7]
[6, 2, 18, 17, 3]
[12, 8, 19, 17, 17]
[6, 10, 10, 10, 12]
[7, 10, 10, 10, 0]
[2, 18, 17, 17, 11]
[4, 4, 5, 10, 3]
[4, 10, 12, 0, 11]
[12, 4, 11, 18, 18]
[4, 0, 10, 5, 18]
[0, 10, 4, 6, 6]
[2, 16, 16, 12, 7]
[12, 17, 17, 17, 11]
[0, 8, 3, 11, 7]
[4, 10, 3, 7, 0]
[8, 6, 3, 11, 0]
[0, 4, 7, 10, 3]
[4, 3, 0, 7, 5]
[7, 8, 4, 3, 11]
[17, 4, 10, 3, 12]
[5, 4, 3, 7, 7]
[3, 7, 2, 18, 12]
[12, 2, 17, 18, 11]
[12, 2, 17, 11, 7]
[12, 3, 2, 7, 8]
[17, 10, 7, 3, 12]
[12, 3, 16, 16, 19]
[16, 16, 9, 13, 13]
[0, 5, 6, 19, 8]
[4, 19, 10, 10, 12]
[4, 7, 7, 17, 17]
[18, 10, 4, 0, 17]
[3, 7, 4, 12, 18]
[4, 10, 18, 0, 19]
[3, 4, 5, 19, 17]
[13, 13, 17, 17, 16]
[18, 10, 7, 5, 5]
[12, 3, 19, 4, 10]
[10, 4, 17, 11, 12]
[7, 4, 3, 10, 12]
[17, 4, 12, 19, 10]
[5, 3, 12, 12, 12]
[2, 12, 9, 19, 6]
[11, 17, 19, 18, 10]
[3, 7, 10, 13, 13]
[8, 0, 